apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: dev
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:  # Corrected 'temoplate' to 'template'
    metadata:
      labels:  # Corrected 'Labels' to 'labels'
        app: mongo
    spec:
      containers:  # Corrected 'container' to 'containers'
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: dev
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 27017

